/**
 * @generated by scripts/generate-color-schemes.src.mjs — do not edit by hand.
 * Run `npm run schemes:generate` after changing seeds or tone mappings.
 */
export interface GeneratedScheme {
	id: string;
	name: string;
	seed: string;
	preview: { bg: string; accent: string; text: string };
	colors: {
		primary: Record<string, string>;
		surface: Record<string, string>;
		tokens: Record<string, string>;
	};
}

export const GENERATED_SCHEMES: GeneratedScheme[] = [
	{
		"id": "synthesis",
		"name": "Synthesis",
		"seed": "#29A449",
		"preview": {
			"bg": "#0d150d",
			"accent": "#69de7b",
			"text": "#dbe5d7"
		},
		"colors": {
			"primary": {
				"50": "#ebffe6",
				"100": "#c6ffc5",
				"200": "#86fb94",
				"300": "#77ed87",
				"400": "#69de7b",
				"500": "#4cc162",
				"600": "#008433",
				"700": "#006e29",
				"800": "#00531d",
				"900": "#003911"
			},
			"surface": {
				"50": "#f2fced",
				"100": "#eaf4e5",
				"200": "#dbe5d7",
				"300": "#bbcbb7",
				"400": "#a0b09d",
				"500": "#859583",
				"600": "#3c4a3b",
				"700": "#232c23",
				"800": "#192219",
				"900": "#151e15",
				"950": "#0d150d"
			},
			"tokens": {
				"surface-base": "#0d150d",
				"surface-container-lowest": "#081008",
				"surface-container-low": "#151e15",
				"surface-container": "#192219",
				"surface-container-high": "#232c23",
				"surface-container-highest": "#2e372d",
				"on-surface": "#dbe5d7",
				"on-surface-variant": "#bbcbb7",
				"outline": "#859583",
				"outline-variant": "#3c4a3b",
				"accent": "#69de7b",
				"accent-strong": "#008433",
				"on-accent": "#003911",
				"on-accent-strong": "#c6ffc5",
				"accent-container": "#00531d",
				"on-accent-container": "#86fb94"
			}
		}
	},
	{
		"id": "graphite",
		"name": "Graphite",
		"seed": "#6b7280",
		"preview": {
			"bg": "#131315",
			"accent": "#c4c6cf",
			"text": "#e4e2e3"
		},
		"colors": {
			"primary": {
				"50": "#f9f9ff",
				"100": "#eef0fa",
				"200": "#e0e2ec",
				"300": "#d2d4dd",
				"400": "#c4c6cf",
				"500": "#a8abb4",
				"600": "#6f727a",
				"700": "#5b5e66",
				"800": "#43474e",
				"900": "#2d3038"
			},
			"surface": {
				"50": "#fbf8fa",
				"100": "#f3f0f1",
				"200": "#e4e2e3",
				"300": "#c7c6c8",
				"400": "#acabad",
				"500": "#919093",
				"600": "#464749",
				"700": "#2a2a2b",
				"800": "#1f1f21",
				"900": "#1b1b1d",
				"950": "#131315"
			},
			"tokens": {
				"surface-base": "#131315",
				"surface-container-lowest": "#0e0e0f",
				"surface-container-low": "#1b1b1d",
				"surface-container": "#1f1f21",
				"surface-container-high": "#2a2a2b",
				"surface-container-highest": "#353536",
				"on-surface": "#e4e2e3",
				"on-surface-variant": "#c7c6c8",
				"outline": "#919093",
				"outline-variant": "#464749",
				"accent": "#c4c6cf",
				"accent-strong": "#6f727a",
				"on-accent": "#2d3038",
				"on-accent-strong": "#eef0fa",
				"accent-container": "#43474e",
				"on-accent-container": "#e0e2ec"
			}
		}
	},
	{
		"id": "black",
		"name": "Black",
		"seed": "#71717a",
		"preview": {
			"bg": "#000000",
			"accent": "#c6c5cf",
			"text": "#e5e1e3"
		},
		"colors": {
			"primary": {
				"50": "#fbf8ff",
				"100": "#f1effa",
				"200": "#e3e1ec",
				"300": "#d4d3dd",
				"400": "#c6c5cf",
				"500": "#abaab4",
				"600": "#71717a",
				"700": "#5d5e66",
				"800": "#46464e",
				"900": "#2f3038"
			},
			"surface": {
				"50": "#fcf8fa",
				"100": "#f3f0f1",
				"200": "#e5e1e3",
				"300": "#c8c6c9",
				"400": "#adaaad",
				"500": "#929093",
				"600": "#3e3d40",
				"700": "#201f21",
				"800": "#161517",
				"900": "#0e0e0f",
				"950": "#000000"
			},
			"tokens": {
				"surface-base": "#000000",
				"surface-container-lowest": "#000000",
				"surface-container-low": "#0e0e0f",
				"surface-container": "#161517",
				"surface-container-high": "#201f21",
				"surface-container-highest": "#2a2a2b",
				"on-surface": "#e5e1e3",
				"on-surface-variant": "#c8c6c9",
				"outline": "#929093",
				"outline-variant": "#474649",
				"accent": "#c6c5cf",
				"accent-strong": "#71717a",
				"on-accent": "#2f3038",
				"on-accent-strong": "#f1effa",
				"accent-container": "#46464e",
				"on-accent-container": "#e3e1ec"
			}
		}
	},
	{
		"id": "blue",
		"name": "Blue",
		"seed": "#3b82f6",
		"preview": {
			"bg": "#0f131c",
			"accent": "#adc6ff",
			"text": "#dfe2ef"
		},
		"colors": {
			"primary": {
				"50": "#f9f9ff",
				"100": "#edf0ff",
				"200": "#d8e2ff",
				"300": "#c3d4ff",
				"400": "#adc6ff",
				"500": "#81aaff",
				"600": "#1b6ee1",
				"700": "#005ac2",
				"800": "#004395",
				"900": "#002e6a"
			},
			"surface": {
				"50": "#f9f9ff",
				"100": "#eef0fd",
				"200": "#dfe2ef",
				"300": "#c0c6d9",
				"400": "#a5abbd",
				"500": "#8a90a2",
				"600": "#404756",
				"700": "#262a33",
				"800": "#1c2029",
				"900": "#181b25",
				"950": "#0f131c"
			},
			"tokens": {
				"surface-base": "#0f131c",
				"surface-container-lowest": "#0a0e17",
				"surface-container-low": "#181b25",
				"surface-container": "#1c2029",
				"surface-container-high": "#262a33",
				"surface-container-highest": "#31353f",
				"on-surface": "#dfe2ef",
				"on-surface-variant": "#c0c6d9",
				"outline": "#8a90a2",
				"outline-variant": "#404756",
				"accent": "#adc6ff",
				"accent-strong": "#1b6ee1",
				"on-accent": "#002e6a",
				"on-accent-strong": "#edf0ff",
				"accent-container": "#004395",
				"on-accent-container": "#d8e2ff"
			}
		}
	},
	{
		"id": "red",
		"name": "Red",
		"seed": "#ef4444",
		"preview": {
			"bg": "#1e100f",
			"accent": "#ffb3ad",
			"text": "#f9dcd9"
		},
		"colors": {
			"primary": {
				"50": "#fff8f7",
				"100": "#ffedeb",
				"200": "#ffdad7",
				"300": "#ffc7c2",
				"400": "#ffb3ad",
				"500": "#ff8982",
				"600": "#d63235",
				"700": "#b91a24",
				"800": "#930013",
				"900": "#68000a"
			},
			"surface": {
				"50": "#fff8f7",
				"100": "#ffedeb",
				"200": "#f9dcd9",
				"300": "#e3bebb",
				"400": "#c6a3a0",
				"500": "#aa8986",
				"600": "#5b403e",
				"700": "#362625",
				"800": "#2b1c1a",
				"900": "#271817",
				"950": "#1e100f"
			},
			"tokens": {
				"surface-base": "#1e100f",
				"surface-container-lowest": "#180b0a",
				"surface-container-low": "#271817",
				"surface-container": "#2b1c1a",
				"surface-container-high": "#362625",
				"surface-container-highest": "#42302f",
				"on-surface": "#f9dcd9",
				"on-surface-variant": "#e3bebb",
				"outline": "#aa8986",
				"outline-variant": "#5b403e",
				"accent": "#ffb3ad",
				"accent-strong": "#d63235",
				"on-accent": "#68000a",
				"on-accent-strong": "#ffedeb",
				"accent-container": "#930013",
				"on-accent-container": "#ffdad7"
			}
		}
	},
	{
		"id": "purple",
		"name": "Purple",
		"seed": "#a855f7",
		"preview": {
			"bg": "#16111b",
			"accent": "#ddb7ff",
			"text": "#eadfed"
		},
		"colors": {
			"primary": {
				"50": "#fff7fe",
				"100": "#faecff",
				"200": "#f0dbff",
				"300": "#e7c9ff",
				"400": "#ddb7ff",
				"500": "#ca93ff",
				"600": "#9945e8",
				"700": "#842bd2",
				"800": "#6900b3",
				"900": "#490080"
			},
			"surface": {
				"50": "#fff7fe",
				"100": "#f8edfc",
				"200": "#eadfed",
				"300": "#cfc2d7",
				"400": "#b4a7bb",
				"500": "#988ca0",
				"600": "#4d4354",
				"700": "#2e2832",
				"800": "#231d28",
				"900": "#1f1923",
				"950": "#16111b"
			},
			"tokens": {
				"surface-base": "#16111b",
				"surface-container-lowest": "#110c16",
				"surface-container-low": "#1f1923",
				"surface-container": "#231d28",
				"surface-container-high": "#2e2832",
				"surface-container-highest": "#39323d",
				"on-surface": "#eadfed",
				"on-surface-variant": "#cfc2d7",
				"outline": "#988ca0",
				"outline-variant": "#4d4354",
				"accent": "#ddb7ff",
				"accent-strong": "#9945e8",
				"on-accent": "#490080",
				"on-accent-strong": "#faecff",
				"accent-container": "#6900b3",
				"on-accent-container": "#f0dbff"
			}
		}
	}
];
