// Generated by scripts/generate-manga-guidance.mjs - DO NOT EDIT BY HAND.
// 
// Source: the frozen Hy-MT2 manga fine-tune glossary config (machine-local).
// Frozen source brief sha256: 414a8ac4b7718f46a5de49b2322a9e89274fcd5ce44e6206e95e27aa358ebf02
// Rendered-block table sha256: 5eb9b8b856b88fcb35030b7533047cc534d83394cd2bea4789c2940cd720aa18
// 
// These are the exact terminology blocks the v3 fine-tune was trained with.
// Editing one silently moves the prompt away from the training distribution;
// regenerate from the frozen config instead.
#pragma once

#include <string>
#include <unordered_map>

namespace fumeto {

// Keyed by TARGET language code. Every block assumes a Japanese source; the
// caller gates on that before looking one up.
inline const std::unordered_map<std::string, std::string> & mangaGuidanceBlocks() {
    static const std::unordered_map<std::string, std::string> blocks = {
        {"ar", "Reference the following manga translations:\n部室 تُترجم إلى «غرفة النادي».\nついたー تُترجم إلى «وصلتُ!».\nよろしくお願いいたします تعبّر عن طلب مهذّب للتعاون، مثل «أرجو تعاونكم»، لا عن أمل عام.\n\n"},
        {"de", "Reference the following manga translations:\n部室 wird im Deutschen mit „Klubraum“ wiedergegeben.\nついたー wird als fröhliches, kurzes „Bin da!“ wiedergegeben.\nよろしくお願いいたします drückt eine höfliche Bitte um Unterstützung oder Zusammenarbeit aus, etwa „Ich bitte um Ihre Unterstützung“, nicht bloß einen allgemeinen Wunsch.\n\n"},
        {"en", "Reference the following manga translations:\n部室 translates to clubroom\nついたー translates to I'm here!\nよろしくお願いいたします expresses a polite request such as \"Please take care of us,\" not a generic hope\n\n"},
        {"es", "Reference the following manga translations:\n部室 se traduce como sala del club.\nついたー se traduce como ¡Ya llegué!\nよろしくお願いいたします expresa una petición formal de colaboración, por ejemplo: «Le agradezco de antemano su apoyo»; no es un saludo genérico.\n\n"},
        {"fa", "Reference the following manga translations:\n部室 در بافت مدرسه به «اتاقِ انجمن» ترجمه می‌شود.\nついたー در گفتار محاوره‌ای به «رسیدم!» ترجمه می‌شود.\nよろしくお願いいたします بیانگر درخواست مؤدبانه برای همکاری یا همراهی است، نه یک امیدواری کلی؛ برای نمونه: «ممنون می‌شوم اگر همکاری کنید.»\n\n"},
        {"fi", "Reference the following manga translations:\n部室 kääntyy koulukerhon yhteydessä luontevasti muotoon ”kerhohuone”.\nついたー on lyhyt ja rento ”Perillä!”, jossa venytys välittyy innostuneena saapumisilmoituksena.\nよろしくお願いいたします ilmaisee kohteliasta yhteistyö- tai palvelupyyntöä; suomeksi se voi olla pragmaattisesti ”Kiitos jo etukäteen.”, ei kirjaimellinen toivotus.\n\n"},
        {"fr", "Reference the following manga translations:\n部室 se traduit par « local du club ».\nついたー se traduit par « Me voilà ! ».\nよろしくお願いいたします exprime une demande polie telle que « Merci d’avance pour votre aide », et non un simple souhait.\n\n"},
        {"hi", "Reference the following manga translations:\n部室 का स्वाभाविक हिन्दी रूप ‘क्लब का कमरा’ है।\nついたー का हल्का, छोटा आगमन-संदेश ‘मैं यहाँ हूँ!’ है।\nよろしくお願いいたします सहयोग माँगने या विनम्र रूप से बात समाप्त करने का भाषण-कर्म है; प्रसंगानुसार ‘आगे भी आपका सहयोग अपेक्षित है।’ कहें, इसे सामान्य शुभकामना न बनाएं।\n\n"},
        {"id", "Reference the following manga translations:\n部室 diterjemahkan sebagai ruang klub\nついたー diterjemahkan sebagai Aku sudah sampai!\nよろしくお願いいたします bukan harapan umum, melainkan permohonan sopan seperti “Mohon kerja samanya.”\n\n"},
        {"it", "Reference the following manga translations:\n部室 si traduce con sala del club\nついたー si traduce con «Eccomi!»\nよろしくお願いいたします esprime una richiesta cortese di collaborazione, per esempio «Conto sulla sua collaborazione», non un generico augurio\n\n"},
        {"ja", "Reference the following manga translations:\n部室は「部室」と訳します。\nついたーは「着いたー！」と訳します。\nよろしくお願いいたしますは、一般的な希望ではなく「どうぞよろしくお願いします」のような丁寧な依頼を表します。\n\n"},
        {"ko", "Reference the following manga translations:\n部室은 동아리방으로 옮깁니다.\nついたー는 도착했음을 알리는 말이므로 ‘도착했어!’로 옮깁니다.\nよろしくお願いいたします는 협조를 구하거나 대화를 공손히 맺는 표현이므로 문맥에 따라 잘 부탁드립니다 또는 부탁드립니다로 옮깁니다.\n\n"},
        {"pl", "Reference the following manga translations:\n部室 tłumaczy się idiomatycznie jako „sala klubowa” w kontekście szkolnego klubu.\nついたー to krótkie, swobodne „Jestem!”, czyli oznajmienie, że mówiący dotarł na miejsce.\nよろしくお願いいたします wyraża uprzejmą prośbę o współpracę; pragmatycznie może znaczyć „Z góry dziękuję”, a nie ogólne życzenie.\n\n"},
        {"pt", "Reference the following manga translations:\n部室 traduz-se idiomaticamente como “sala do clube”.\nついたー pode ser “Cheguei!”, um anúncio casual e curto de que a pessoa chegou ao local.\nよろしくお願いいたします expressa um pedido cortês de cooperação — por exemplo, “Conto com sua colaboração.” —, não um desejo genérico.\n\n"},
        {"ru", "Reference the following manga translations:\n部室 переводится как «комната клуба» в школьном контексте.\nついたー переводится как «Я здесь!»; «Я пришёл!» или «Я пришла!» уместно, когда сцене важно подчеркнуть прибытие.\nよろしくお願いいたします выражает вежливую просьбу или ожидание содействия: «Заранее благодарю за помощь», а не буквальное пожелание.\n\n"},
        {"sv", "Reference the following manga translations:\n部室 översätts idiomatiskt som ”klubbrum” i en skolklubbskontext.\nついたー blir det korta, lediga ”Framme!”, en glad signal om att talaren har kommit fram.\nよろしくお願いいたします uttrycker en artig begäran om samarbete; på svenska kan det pragmatiskt bli ”Tack på förhand.”, inte en allmän förhoppning.\n\n"},
        {"th", "Reference the following manga translations:\n部室 แปลในบริบทชมรมโรงเรียนอย่างเป็นธรรมชาติว่า “ห้องชมรม” ไม่ใช่ห้องเรียนหรือห้องสโมสรทั่วไป\nついたー เป็นคำประกาศสั้น ๆ แบบกันเองเมื่อมาถึง: “ถึงแล้ว!” คงความดีใจและความยืดของเสียงตามพื้นที่บอลลูน\nよろしくお願いいたします แสดงเจตนาตามบริบท: เมื่อแนะนำตัว ผู้พูดชายใช้ “ขอฝากตัวด้วยนะครับ” และผู้พูดหญิงใช้ “ขอฝากตัวด้วยนะคะ”; เมื่อขอความร่วมมือหรือขอให้อีกฝ่ายช่วย ผู้พูดชายใช้ “รบกวนด้วยนะครับ” และผู้พูดหญิงใช้ “รบกวนด้วยนะคะ” หรือเลือกคำขอสุภาพอื่นที่ตรงฉาก ไม่ใช่คำอวยพรหรือความหวังทั่วไป\n\n"},
        {"tr", "Reference the following manga translations:\n部室, okul kulübü bağlamında doğal olarak “kulüp odası” diye çevrilir.\nついたー, kısa ve samimi bir varış duyurusu olarak “Geldim!” diye çevrilebilir.\nよろしくお願いいたします genel bir dilek değil, bağlama göre nazik bir iş birliği veya yardım talebidir; pragmatik olarak “İş birliğiniz için şimdiden teşekkür ederim.” denebilir.\n\n"},
        {"uk", "Reference the following manga translations:\n部室 у шкільному контексті природно перекладається як «кімната гуртка».\nついたー — коротке, невимушене «Я вже тут!», жваве повідомлення про прибуття без нав’язаного роду.\nよろしくお願いいたします висловлює ввічливе прохання про співпрацю; прагматично: «Заздалегідь дякую за допомогу», а не загальне побажання.\n\n"},
        {"vi", "Reference the following manga translations:\n部室 có thể dịch là “phòng câu lạc bộ”.\nついたー có thể dịch là “Tới rồi!” khi người nói báo đã đến; chỉ thêm đại từ nếu ngữ cảnh xác định.\nよろしくお願いいたします diễn đạt lời nhờ vả hoặc mong tiếp tục hợp tác một cách lịch sự; chọn câu đích theo quan hệ và tình huống, không gắn sẵn đại từ.\n\n"},
        {"zh-Hans", "Reference the following manga translations:\n部室对应“社团活动室”\nついたー译为“我到了！”（轻快的到达宣告）\nよろしくお願いいたします表达礼貌的请求或托付，可译为“请多关照”或“麻烦您了”，不是泛泛的“希望顺利”\n\n"},
    };
    return blocks;
}

/**
 * The guidance block for a Japanese-source translation into `targetCode`, or
 * an empty string when the target has none. An unknown target deliberately
 * yields no guidance rather than the English block: the wrong language's
 * terminology in the prompt is worse than none.
 */
inline std::string mangaGuidanceFor(const std::string & sourceCode, const std::string & targetCode) {
    if (sourceCode != "ja") return std::string();
    const auto & blocks = mangaGuidanceBlocks();
    const auto it = blocks.find(targetCode);
    return it == blocks.end() ? std::string() : it->second;
}

}  // namespace fumeto
